version: '2'
services:
  backend:
    container_name: quote_bot
    image: quote_bot
    restart: unless-stopped
    build: .
    ports:
      - "9092:9092"
    environment:
      - BOT_NAME=$BOT_NAME
      - BOT_TOKEN=${BOT_TOKEN}
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASSWORD=${SECURITY_PASSWORD}
      - QUOTES_API_URL=${QUOTES_API_URL}