version: '2'
services:
  backend:
    container_name: quote_bot
    image: quote_bot
    mem_limit: 250m
    mem_reservation: 200M
    restart: unless-stopped
    build: .
    ports:
      - "9092:9092"
    environment:
      - JAVA_OPTS=-Xmx180m
      - BOT_NAME=$BOT_NAME
      - BOT_TOKEN=${BOT_TOKEN}
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASSWORD=${SECURITY_PASSWORD}
      - QUOTES_API_URL=${QUOTES_API_URL}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=${QUOTE_DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - QUES_BOT_NAME=${QUES_BOT_NAME}
      - QUES_BOT_TOKEN=${QUES_BOT_TOKEN}